name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run backend tests (if any)
        run: |
          cd backend
          if [ -f "test.sh" ]; then bash test.sh; else echo "No test.sh found"; fi

      - name: Build project
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Deploy (dry run)
        run: |
          chmod +x deploy.sh
          ./deploy.sh --dry-run

      - name: Lint shell scripts
        run: |
          sudo apt-get update && sudo apt-get install -y shellcheck
          shellcheck **/*.sh || true
